


# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
title: Ben S. Duggan
email: dugganbens@gmail.com
description: The personal website of Ben Duggan
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BenSDuggan
github_username:  BenSDuggan

###################
## Site settings  #
###################
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Ben S. Duggan" # Site name or title, also used in jekyll-seo-tag
#logo: "" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "https://bensduggan.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/BenSDuggan"
email: "dugganbens@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


###################
# Site navigation #
###################
navigation_header:
- title: Home
  url: /
- title: About
  url: /about
- title: Projects
  url: /projects.html
- title: Blog
  url: /blog.html

navigation_footer:
- title: Home
  url: /

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/BenSDuggan
  email: dugganbens@gmail.com
  Twitter: https://twitter.com/BenSDuggan
  LinkedIn: https://www.linkedin.com/in/ben-duggan-b3a860164/


# Collections
collections:
  projects:
    title: Projects
    output: true
    description: "Research and personal projects"


# sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#   Twitter: "#0d94e7"
#   facebook: "#3B5998"
#   Email: true
